__GLOBAL__.appRegister = {};
__GLOBAL__.nodeIdCache = {};
__GLOBAL__.nodeTreeCache = {};
__GLOBAL__.nodeParamCache = {}; // Not necessary for Android, but need for clean.
__GLOBAL__.moduleCallId = 0;
__GLOBAL__.moduleCallList = {};
__GLOBAL__.DimensionsStore = {}; // TODO: Able to delete
__GLOBAL__.canRequestAnimationFrame = true;
__GLOBAL__.requestAnimationFrameId = 0;
__GLOBAL__.requestAnimationFrameQueue = {};
__GLOBAL__.const = {}; // TODO: Able to delete
__GLOBAL__.destroyInstanceList = {};
