/* Tencent is pleased to support the open source community by making Hippy available.
 * Copyright (C) 2018 THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_mtt_hippy_bridge_HippyBridgeImpl */

#ifndef _Included_com_tencent_mtt_hippy_bridge_HippyBridgeImpl
#define _Included_com_tencent_mtt_hippy_bridge_HippyBridgeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_mtt_hippy_bridge_HippyBridgeImpl
 * Method:    initJSFramework
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_initJSFramework
  (JNIEnv *, jobject, jbyteArray, jboolean, jboolean, jboolean, jobject, jlong);

/*
 * Class:     com_tencent_mtt_hippy_bridge_HippyBridge
 * Method:    runScriptFromFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_runScriptFromFile
  (JNIEnv *, jobject, jstring, jstring, jboolean, jstring,jlong, jobject);

/*
* Class:     com_tencent_mtt_hippy_bridge_HippyBridge
* Method:    runScriptFromAssets
* Signature: (Ljava/lang/String;JObject;Z;Ljava/lang/String;J)Z
*/
JNIEXPORT jboolean JNICALL Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_runScriptFromAssets
(JNIEnv *, jobject, jstring, jobject, jboolean, jstring,jlong, jobject);

/*
 * Class:     com_tencent_mtt_hippy_bridge_HippyBridgeImpl
 * Method:    destroy
 * Signature: (J;Z)V
 */
JNIEXPORT void JNICALL Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_destroy
  (JNIEnv *, jobject, jlong, jboolean, jobject);

/*
 * Class:     com_tencent_mtt_hippy_bridge_HippyBridgeImpl
 * Method:    callFunction
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_callFunction
  (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jlong, jobject);

/*
 * Class:     com_tencent_mtt_hippy_bridge_HippyBridgeImpl
 * Method:    runNativeRunnable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_runNativeRunnable
  (JNIEnv *, jobject, jstring, jlong, jlong, jobject);

JNIEXPORT jstring JNICALL Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_getCrashMessage
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL
Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_runOnJSThread(JNIEnv *env, jobject thiz,
                                                                jlong runtime_id,
                                                                jobject runnable);
JNIEXPORT jlongArray JNICALL
Java_com_tencent_mtt_hippy_bridge_HippyBridgeImpl_getV8Runtime(JNIEnv *env, jobject thiz,
                                                               jlong runtime_id);

#ifdef __cplusplus
}
#endif
#endif
