platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false, :disable_input_output_paths => true

def run_devtools_cmake
  system("rm -rf devtools_backend")
  system("mkdir devtools_backend")
  system("cmake ../../../../devtools/devtools-backend/CMakeLists.txt -B ./devtools_backend -G Xcode -DMODULE_TOOLS=YES -DCMAKE_TOOLCHAIN_FILE=./ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DENABLE_BITCODE=YES -DENABLE_ARC=YES -DDEPLOYMENT_TARGET=11.0 -DENABLE_INSPECTOR=YES")
end

pre_install do |installer|
  if system("command -v cmake > /dev/null")
     run_devtools_cmake
  else
     puts "\n#####################################################\n"
     raise "cmake is not installed, use `brew install cmake` to install cmake "
  end
end

workspace 'HippyDemo.xcworkspace'
project 'HippyDemo.xcodeproj'

target 'HippyDemo' do
end
