name: HippyDemo
options:
  createIntermediateGroups: true
  bundleIdPrefix: "com.tencent"
  xcodeVersion: "10.0"
  postGenCommand: pod update
targets:
  HippyDemo:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    settings:
      OTHER_LDFLAGS: "${inherited}"
      TARGETED_DEVICE_FAMILY: "1"
      CLANG_CXX_LANGUAGE_STANDARD: "c++17"
      PRODUCT_BUNDLE_IDENTIFIER: "com.tencent.HippyDemo2.db"
    sources:
      - path: HippyDemo
      - path: Assets.xcassets
      - path: fonts
        buildPhase: 
          copyFiles:
            destination: "resources"
      - path: res
        type: "folder"
