name: HippyDemo
options:
  createIntermediateGroups: true
  bundleIdPrefix: "com.tencent"
  xcodeVersion: "10.0"
  postGenCommand: pod update
targets:
  HippyDemo:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    settings:
      OTHER_LDFLAGS: "-ObjC -force_load \"${PODS_CONFIGURATION_BUILD_DIR}/HippyBase/libHippyBase.a\" -force_load \"${PODS_CONFIGURATION_BUILD_DIR}/HippyJSDriver/libHippyJSDriver.a\" -force_load \"${PODS_CONFIGURATION_BUILD_DIR}/HippyFramework/libHippyframework.a\" -force_load \"${PODS_CONFIGURATION_BUILD_DIR}/HippyNativeRender/libHippyNativeRender.a\" -force_load \"${PODS_CONFIGURATION_BUILD_DIR}/HippyDevTools/libHippyDevTools.a\""
      TARGETED_DEVICE_FAMILY: "1"
      CLANG_CXX_LANGUAGE_STANDARD: "c++17"
    sources:
      - path: HippyDemo
      - path: fonts
        buildPhase: 
          copyFiles:
            destination: "resources"
      - path: res
        type: "folder"