install! 'cocoapods', :deterministic_uuids => false

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'HippyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for HippyDemo
  pod 'hippy', :path=>'../../'

end
