# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mengyanluo/work_project/HippyCode/GithubHippy_3.0/buildconfig/cmake/compiler_toolchain.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mengyanluo/work_project/HippyCode/GithubHippy_3.0/modules/footstone/CMakeLists.txt))

/Users/mengyanluo/work_project/HippyCode/GithubHippy_3.0/framework/example/ios-demo/devtools_backend/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.23.2/bin/cmake -H/Users/mengyanluo/work_project/HippyCode/GithubHippy_3.0/devtools/devtools-backend -B/Users/mengyanluo/work_project/HippyCode/GithubHippy_3.0/framework/example/ios-demo/devtools_backend
