# .code.yml规则检查：https://iwiki.woa.com/pages/viewpage.action?pageId=168736953
#
# 扫描代码规范、圈复杂度
# https://iwiki.woa.com/pages/viewpage.action?pageId=877903730#TDF工程化集成EPC-code-style代码规范
code-style:
    # 打印更多调试信息
    debug: false
    # 增量扫描模式
    patch-mode: true
    # 最大报告条数；同时作用于圈复杂度和代码规范两个报告
    max-report-count: 50
    # 开启代码规范扫描
    enable-style: true
    # 开启圈复杂度扫描
    enable-ccn: true
    # 拦截代码规范问题，默认开启
    intercept-style: true
    # 拦截圈复杂度超标问题，默认开启
    intercept-ccn: true
    # 是否只扫描变更行，默认开启，关闭后会扫描有变更的整个文件
    line-scan: false
    # 自定义圈复杂度扫描阈值
    ccn: 0
    # 自定义千行超标数
    kloc: 0
    # 语言通用的圈复杂度质量级别，参考epc规范 https://iwiki.woa.com/pages/viewpage.action?pageId=23593267
    # cnn-level存在时，cnn和kloc失效
    ccn-level: 4
    
    # 每一种扫描语言的配置
    cpp:
        # 当前语言所扫描的文件夹，只允许相对路径；不支持正则
#        scan-dirs:
#        - data
        # 规范文件，默认使用自更新的腾讯统一代码规范
        code-style-file: ""
        # 排除的路径，可以为正则
        exclusion-paths:
        - third_party
        # 展示的错误等级，可选：warn/error/info，默认全部展示，例如设置为warn，则info级的问题不再被报告
        level: ""
        # 语言使用的扫描工具，默认为 code-style-{language}，非特殊情况不建议更改
        tool-name: ""
        # 当前语言所用的圈复杂度质量级别，优先级高于语言通用的ccn-level
        ccn-level: 4
        
#    go:
#
#    java:
  
# 提交日志规范纠正
# https://iwiki.woa.com/pages/viewpage.action?pageId=877903730#TDF工程化集成EPC-3.2提交日志规范
log-helper:
    debug: false
    # 启用自动纠正能力
    auto-correct: true
    # 是否纠正angular规范
    correct-angular: true
    # 是否纠正tapd规范
    correct-tapd: true

# 分支检查工具
# https://iwiki.woa.com/pages/viewpage.action?pageId=877903730#TDF工程化集成EPC-3.3分支命名规范
branch:
    # 主干，推荐命名为master
    trunk_name: "master"
    # 分支类型A分支命名规范定义，若项目未使用该分支类型，请删除该类型的分支命名定义
    branch_type_A:
        personal_feature:
          pattern: "feature/${userID}_${storyID}"
        bugfix:
          pattern: "bugfix/${userID}_${bugID}"
        tag:
          pattern: "v${versionnumber}[${releasetype}[_${description}]{_yyyyMMddHHmm}]"
          versionnumber: "versionnumber={Major-version}.{Feature-version}.{Fix-version}.{BuildNo}"

# 必须要有整个节点并且artifact_type不能为空
# https://iwiki.woa.com/pages/viewpage.action?pageId=877903730#TDF工程化集成EPC-3.4发布制品、依赖制品配置规范
artifact:
 - path: /
   artifact_type : "终端"

# 文件说明
# https://iwiki.woa.com/pages/viewpage.action?pageId=877903730#TDF工程化集成EPC-3.5文件owner和代码评审配置规范
file:
- path: demoHeader.cpp
  owners:  ["sicilyliu"]
  owner_rule: -1

# 配置钩子，用来开启或者关闭检测项
# https://iwiki.woa.com/pages/viewpage.action?pageId=877903730#TDF工程化集成EPC-3.6各项拦截开关
# hookman:
#    debug: false
#    focus: true
#    features:
#    - code-style
#    - correct-commit-msg
#    - epc-commit-check




