# 代码规范检查
.run-cpplint: &run-cpplint
  name: run cpplint
  jobs:
    - name: make changelist
      type: git:changeList
      options:
        changed: changed.txt
    - name: cat all changed files
      script: cat changed.txt
      exports:
        stdout: ALL_CHANGED_FILES
    - name: cpplint job
      image: csighub.tencentyun.com/hippy/cpplint:latest
      settings:
        files: ${ALL_CHANGED_FILES}

# 提交注释检查
.run-commit-lint: &run-commit-lint
  name: run commit lint
  type: epc:commit-lint

# 跑单测覆盖率
.run-coverage: &run-coverage
  name: run coverage stage
  jobs:
    - name: generate coverage file
      script:
        - cd test
        - sh build.sh
    - name: upload qcoverage
      type: qcoverage:upload
      #      options:
      #        lines: ge # 覆盖率行结果不能下降
      #        functions: ge # 覆盖率函数结果必须上升
      #        branches: ge # 覆盖率分支结果必须上升
      #        diffLines: 10 # 每次提交变更增量覆盖率必须达到10或以上
      envExport:
        url: QCOV_LINE_URL
        lines: COV_PCT
        diff_pct: DIFF_PCT
        diff_total: DIFF_TOTAL
        diff_covered: DIFF_COVERED

# 单测覆盖率通知所有人
.notify-all-coverage: &notify-all-coverage
  name: 通知所有人的单测覆盖率
  type: wework:message
  options:
    robot: c2ce0ac8-5dc6-4f3c-a10d-3a889daac3b5
    message: |
      > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
      >
      > [全量覆盖率](${QCOV_LINE_URL}): ${COV_PCT}%
      > 增量覆盖率: ${DIFF_PCT}% (${DIFF_COVERED}/${DIFF_TOTAL})
      > 　
      > from ${ORANGE_BUILD_USER}

# mac构建机安装工具
.mac-install-tools: &mac-install-tools
  name: mac构建机安装工具
  script:
    - git clone https://github.com/linux-test-project/lcov.git
    - cd lcov
    - make install

# 发送到 CR 专用群
.notify-cr-to-wechat: &notify-cr-to-wechat
  name: send cr to wechat
  type: wework:message
  options:
    robot: c2ce0ac8-5dc6-4f3c-a10d-3a889daac3b5
    message: |
      > 发送到 CR 专用群
      > 　
      > ${ORANGE_MERGE_REQUEST_TITLE}
      > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
      > 　
      > from ${ORANGE_BUILD_USER}

.personal-push-pipeline: &personal-push-pipeline
  name: personal push pipeline
  runner:
    network: devnet-mac
    MacOS: "11.4"
    XCode: "11.4"
  docker:
    image: node:12
  stages:
    - *mac-install-tools
    - *run-commit-lint
    - *run-coverage

.personal-mr-pipeline: &personal-mr-pipeline
  name: personal mr pipeline
  stages:
    - *run-commit-lint
    - *run-cpplint
    - *notify-cr-to-wechat

master:
  review:
    - name: review流水线
      stages:
        - name: CR 通过后自动合并
          type: git:automerge
          options:
            mergeType: rebase
            removeSourceBranch: true
            ignoreAssignee: true
          exports:
            reviewedBy: REVIEWED_BY
        - name: notify
          type: wework:message
          options:
            robot: c2ce0ac8-5dc6-4f3c-a10d-3a889daac3b5
            chatId: wrkSFfCgAAblj2-ADZf0aMZz28em4FZQ
            visibleToUser: ${ORANGE_BUILD_USER}
            message: |
              > CR 通过后自动合并 <@${ORANGE_BUILD_USER}>
              > 　
              > ${ORANGE_MERGE_REQUEST_TITLE}
              > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
              >
              > ${REVIEWED_BY}

  merge_request:
    - name: MR 流水线
      runner:
        network: devnet-mac
        MacOS: "11.4"
        XCode: "11.4"
      docker:
        image: node:12
      stages:
        - *run-commit-lint
        - *mac-install-tools
        - *run-cpplint
        - *run-coverage
        - *notify-all-coverage

        # issue 状态检查，是否正确的扭转状态
        - name: issue lint
          type: git:issueUpdate
          options:
            lint:
              # 检查 issue 当前是否处于，accepted 或 resolved状态
              acceptance:
                - accepted
                - resolved

        # 改orange-ci配置、code.yml配置，需要sicily一起看看
        - name: change yml file need review
          ifModify:
            - '.orange-ci.yml'
            - '.code.yml'
          type: git:review
          options:
            type: add-reviewer
            reviewers: sicilyliu

        - *notify-cr-to-wechat

  push:
    # push 编译流水线
    - name: master push 编译流水线
      runner:
        network: devnet
      # 流水线标识
      label:
        type:
          - MASTER
        class:
          - MAIN
      stages:
        # 更新 issue 状态为已解决并关闭，对应 EPC 考核中的 开发完成时间点
        - name: update issue
          type: git:issueUpdate
          options:
            state: close
            acceptance: resolved

  # MR定时通知流水线
  'sicilyliu-crontab: 30 10 * * 1-5':
    - stages:
        - name: 获取 MR 提醒消息
          type: git:mr-remind-message
          exports:
            reviewRemindMessage: REVIEW_REMIND_MESSAGE

        - name: 发送 MR 待处理提醒到企业微信
          type: wework:message
          # 如果待处理 MR 为空，则不发送提醒
          if: |
            [ -n "$REVIEW_REMIND_MESSAGE" ]
          options:
            robot: 9a8a9510-0dcd-41dc-8c6b-9788074bf299
            message: |
              > ${REVIEW_REMIND_MESSAGE}
              >
              > <@所有人> 今天上午之前记得 CR 代码~

feature/*:
  push:
    - *personal-push-pipeline
  merge_request:
    - *personal-mr-pipeline

personal/*:
  push:
    - *personal-push-pipeline
  merge_request:
    - *personal-mr-pipeline

$:
  tag_push:
    - name: tag push 流水线
      label:
        type: RELEASE
      network: idc-kvm

      stages:
        # 自动生成 CHANGELOG.md
        - name: changelog
          type: git:changeLog
          options:
            filename: CHANGELOG.md
            target: master
          exports:
            latestChangeLog: LATEST_CHANGE_LOG

        # 更新 release 的描述，release 如不存在会自动创建
        - name: upload release
          type: git:release
          options:
            description: ${LATEST_CHANGE_LOG}

        # 更新 issue 状态，增加标签，对应 EPC 考核中的 lead time 结束时间点
        - name: update issue
          type: git:issueUpdate
          options:
            fromText: ${LATEST_CHANGE_LOG}
            label:
              add: 需求已接收
            when:
              label: feature

        # 自动上架组件市场
