name: '[markdown-lint] check documents format'

on:
  push:
    paths:
      - '*.md'
      - 'docs/**/*.md'
    branches:
      # Push events on main branch
      - main
      # Push events on master branch
      - master
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - '*.md'
      - 'docs/**/*.md'
    branches:
      # Pull request events to main branch
      - main
      # Pull request events to master branch
      - master
    tags-ignore:
      - '**'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          config_file: .markdownlintrc.json
          files: ./README*.md ./PUBLISH*.md ./docs/**/*.md
