name: '[gh] pull request review'

on:
  pull_request_review:
    types: [ submitted, edit ]

jobs:
  pull_request_review:
    if: github.repository == 'Tencent/Hippy'
    runs-on: ubuntu-latest
    steps:
    - name: Commit
      env:
        REVIEW_INFO: ${{ toJSON(github.event) }}
      run: |
        echo $REVIEW_INFO > ./review_info
    - name: Push
      uses: actions/upload-artifact@v3
      with:
        name: review_info
        path: ./review_info
