name: '[hip] list artifacts'

on:
  workflow_dispatch:
    inputs:
      hip_domain:
        description: 'HIP <domain>'
        type: choice
        options:
        - hippy
        - test
        default: 'hippy'
        required: true
      hip_path:
        description: 'HIP <path>(without domain)'
        type: string

jobs:
  list_artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install Requirement
      run: |
        pip install coscmd
        coscmd config -a ${{ secrets.TC_SECRET_ID }} -s ${{ secrets.TC_SECRET_KEY }} -b ${{ secrets.COS_BUCKET }} -r ${{ secrets.COS_REGION }}
    - name: Publish artifact
      run: |
        coscmd list ${{ github.event.inputs.hip_domain }}/${{ github.event.inputs.hip_path }} -ar >> $GITHUB_STEP_SUMMARY
