name: '[pods] pod spec lint'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'framework/ios/**'
      - 'framework/examples/ios-demo/**'
      - 'driver/js/src/**'
      - 'driver/js/include/**'
      - 'dom/include/**'
      - 'dom/src/**'
      - 'layout/engine/**'
      - 'modules/ios/**'
      - 'modules/footstone/**'
      - 'modules/vfs/ios/**'
      - 'modules/vfs/native/**'
      - 'renderer/native/ios/**'
      - 'devtools/devtools-backend/**'

jobs:
  pod_spec_lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Pod Spec Lint
        run: |
          pod spec lint hippy.podspec --allow-warnings --use-libraries --verbose --skip-import-validation
