name: '[pods] pod spec lint'

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'framework/ios/**'
      - 'framework/examples/ios-demo/**'
      - 'driver/js/src/**'
      - 'driver/js/include/**'
      - 'dom/include/**'
      - 'dom/src/**'
      - 'layout/engine/**'
      - 'modules/ios/**'
      - 'modules/footstone/**'
      - 'modules/vfs/ios/**'
      - 'modules/vfs/native/**'
      - 'renderer/native/ios/**'
      - 'devtools/devtools-backend/**'

jobs:
  ios_build_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Pod_Spec_Lint_Bypass
        run: |
          echo "No Pod Spec Lint required"
