name: '[voltron] build tests'

on:
  pull_request:
    branches:
      - main
      - master
      - v3.0-dev
      - v3.0
    paths-ignore:
      - 'renderer/voltron/**'
      - 'framework/voltron/**'

jobs:
  voltron_build_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Build Test Bypass
      run: |
        echo "No build test required"
