name: '[voltron] build tests'

on:
  pull_request:
    branches:
      - main
      - master
      - v3.0-dev
      - v3.0
    paths:
      - 'renderer/voltron/**'
      - 'framework/voltron/**'
      - 'devtools/**'
      - 'dom/**'
      - 'driver/js/include/**'
      - 'driver/js/src/**'

defaults:
  run:
    working-directory: framework/voltron/example

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  voltron_framework_flutter_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - name: framework flutter pub get
        run: flutter pub get
      - name: framework flutter analyze
        run: flutter analyze
        working-directory: framework/voltron

  voltron_renderer_flutter_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - name: renderer flutter pub get
        run: flutter pub get
      - name: renderer flutter analyze
        run: flutter analyze
        working-directory: renderer/voltron

  voltron_renderer_flutter_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - name: renderer flutter pub get
        run: flutter pub get
      - name: renderer flutter test
        run: flutter test
        working-directory: renderer/voltron

  voltron_android_flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - name: flutter pub get
        run: flutter pub get
      - name: Build for Android
        run: flutter build apk

  voltron_ios_xcframework_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build framework for iOS
        run: python3 script/build.py -os ios -arch arm64 -rebuild
        working-directory: framework/voltron

  voltron_ios_flutter_build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
          architecture: x64
      - name: flutter pub get
        run: flutter pub get
      - name: Build for iOS
        run: flutter build ios --release --no-codesign
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
